completed react-app-drawer-component exercise.
joseph-w-valdez/c1222-code-solutions pull request #121
Opened 2023-02-08 20:19 UTC by joseph-w-valdez

https://user-images.githubusercontent.com/117682160/217642096-6d5d9de0-dd39-45fb-b359-67b232059747.mp4

2023-02-08 20:30 UTC, RobertGardner approved these changes
Looks good!

2023-02-08 20:30 UTC, RobertGardner commented on react-app-drawer-component/src/components/Burger.jsx
> +  const [toggle, setToggle] = useState(false);
`toggle` is a strange state name in my opinion. Usually state is a noun or adjective, but I tend to read toggle as a verb. I would prefer `open` or `isOpen` or something like that.

2023-02-08 20:30 UTC, RobertGardner commented on react-app-drawer-component/src/components/Burger.jsx
> +        <div className="burger top-burger"></div>
Interesting approach to drawing the burger menu. Usually we'd just use FontAwesome.

2023-02-08 20:30 UTC, RobertGardner commented on react-app-drawer-component/src/components/Burger.jsx
> +        <h3 onClick={handleToggle}>About</h3>
Nice. See if you can figure out how to log a message telling you which item was clicked on.

2023-02-08 22:09 UTC, joseph-w-valdez commented on react-app-drawer-component/src/components/Burger.jsx
> +  const [toggle, setToggle] = useState(false);
makes sense. i'll make that change

2023-02-08 22:10 UTC, joseph-w-valdez commented on react-app-drawer-component/src/components/Burger.jsx
> +        <div className="burger top-burger"></div>
I just liked this way so I could animate the burger turning into a cross and then back.

2023-02-08 22:16 UTC, joseph-w-valdez commented
https://user-images.githubusercontent.com/117682160/217663561-742dddfb-0e3a-4d48-aa26-1ffb059fb61e.mp4

2023-02-08 22:21 UTC, RobertGardner requested changes

2023-02-08 22:21 UTC, RobertGardner commented on react-app-drawer-component/src/components/Burger.jsx
> +        <div className="burger top-burger"></div>
Cool! I didn't notice that since I didn't look at the CSS (and may not have understood it if I had!).

2023-02-08 22:21 UTC, RobertGardner commented on react-app-drawer-component/src/components/Burger.jsx
> +        <h1 onClick={(e) => handleToggle(e)} id="menu">Menu</h1>
This is really close. However, it's best not to rely on the component ID since that is in the DOM and can be changed behind your back or by a subsequent code edit.

Notice that when you call `handleToggle` you know what item you have. Try passing that in directly to the function. (You might want a different function that doesn't expect an event as its parameter.)

2023-02-08 22:45 UTC, joseph-w-valdez commented
https://user-images.githubusercontent.com/117682160/217668240-c86b16f5-4d3a-422a-8ee6-639396e33e17.mp4

2023-02-09 16:51 UTC, RobertGardner approved these changes
I suggest looking again at how you determine what was clicked.

2023-02-09 16:51 UTC, RobertGardner commented on react-app-drawer-component/src/components/Burger.jsx
> +    if (event.target.innerText) {
See if you can do this without using `innerText`. In a more general app, you will want to have the object represented by the menu click, not just its text.

2023-02-09 17:02 UTC, joseph-w-valdez commented on react-app-drawer-component/src/components/Burger.jsx
> +    if (event.target.innerText) {
I'll make the changes suggested from the example yesterday. Ty!

2023-02-09 18:14 UTC, joseph-w-valdez commented
https://user-images.githubusercontent.com/117682160/217901678-4505f3ec-c012-4f91-a585-42e0605b6924.mp4

2023-02-13 15:55 UTC, joseph-w-valdez commented
https://user-images.githubusercontent.com/117682160/218506919-e344cfd3-d5f8-44e4-8597-92bce4fc3fa5.mp4

2023-03-08 17:13 UTC, merged