Css canvas medical
joseph-w-valdez/c1222-code-solutions pull request #21
Opened 2022-12-10 00:21 UTC by joseph-w-valdez

![0OnlMtY](https://user-images.githubusercontent.com/117682160/206817997-089a4682-26c0-4ebc-8776-ef9f34d20f09.png)
![UFVeHbC](https://user-images.githubusercontent.com/117682160/206818001-ea59f803-899b-4aa8-aa35-a0b51ead251e.png)

https://user-images.githubusercontent.com/117682160/206818007-4b86cf2f-ed9c-4afe-95af-a0123fae1676.mp4

2022-12-13 18:39 UTC, codingcodymiller requested changes

2022-12-13 18:39 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +    </div>
You should have `column` classes involved here. Direct children of a `row` should always have a `column` class

2022-12-13 18:46 UTC, joseph-w-valdez commented on css-canvas-medical/index.html
> +    </div>
i'll amend this

2022-12-16 23:34 UTC, codingcodymiller approved these changes

2022-12-17 00:29 UTC, merged