completed javascript-if exercise
joseph-w-valdez/c1222-code-solutions pull request #31
Opened 2022-12-14 18:10 UTC by joseph-w-valdez

![GxC0Csq](https://user-images.githubusercontent.com/117682160/207673581-b21ad336-b568-452f-a877-84aff808b1b8.png)

2022-12-16 20:11 UTC, codingcodymiller requested changes

2022-12-16 20:11 UTC, codingcodymiller commented on javascript-if/main.js
> +  return people[person].age >= 21;
You shouldn't be using `people` here, just `person`

2022-12-16 21:47 UTC, joseph-w-valdez commented on javascript-if/main.js
> +  return people[person].age >= 21;
i'll fix it

2022-12-16 21:53 UTC, joseph-w-valdez commented
![Rd0iA3g](https://user-images.githubusercontent.com/117682160/208195115-683549ff-4bd3-4367-9498-4b3df2a236cb.png)

2022-12-16 22:53 UTC, codingcodymiller requested changes

2022-12-16 22:53 UTC, codingcodymiller commented on javascript-if/main.js
> +  return string.split('')[0] === 'J';
`split` is not necessary here

2022-12-16 23:01 UTC, joseph-w-valdez commented
![xpttjGV](https://user-images.githubusercontent.com/117682160/208202576-1c131e97-fff0-40ce-8fb3-7b16f9c436ca.png)

2022-12-19 17:44 UTC, codingcodymiller approved these changes

2022-12-19 17:56 UTC, merged