completed javascript-loops-practice exercise
joseph-w-valdez/c1222-code-solutions pull request #34
Opened 2022-12-15 20:31 UTC by joseph-w-valdez

![Ow8duPp](https://user-images.githubusercontent.com/117682160/207960997-d92c98c6-9de2-41ff-9c97-929a3d1c071d.png)

2022-12-16 23:20 UTC, codingcodymiller requested changes

2022-12-16 23:20 UTC, codingcodymiller commented on javascript-loops-practice/get-student-names.js
> +    for (const prop in students[i]) {
This will save all properties in the object, not just `name`

2022-12-19 17:50 UTC, codingcodymiller requested changes

2022-12-19 17:50 UTC, codingcodymiller commented on javascript-loops-practice/get-student-names.js
> +      }
You should just do `result.push(students[i].name)`

2022-12-19 17:50 UTC, codingcodymiller commented on javascript-loops-practice/includes-seven.js
>  }
This can all be condensed to this:
```
function includesSeven(array) {
  for (var i = 0; i < array.length; i++) {
    if (array[i] === 7) {
        return true;
    }
  }
  return false;
}
```

2022-12-19 18:07 UTC, joseph-w-valdez commented
![image](https://user-images.githubusercontent.com/117682160/208491349-d05385c3-ba79-455b-b5ce-97087454843e.png)

2022-12-27 17:22 UTC, codingcodymiller approved these changes

2022-12-27 17:39 UTC, merged