completed string-manipulation-2 exercise
joseph-w-valdez/c1222-code-solutions pull request #41
Opened 2022-12-18 06:18 UTC by joseph-w-valdez

![toJXvpv](https://user-images.githubusercontent.com/117682160/208284492-c6df6199-8eb8-49cb-baca-9212a19120cb.png)
![iGqI2Tq](https://user-images.githubusercontent.com/117682160/208284493-aeeeddac-d0a3-4ab3-9a8b-ba9b81cf2fb5.png)

2023-01-19 17:51 UTC, codingcodymiller requested changes

2023-01-19 17:51 UTC, codingcodymiller commented on string-manipulation-2/string-manipulation-2/src/capitalize-word.js
> +    result = result.slice(0, 4) + result.slice(4, 5).toUpperCase() + result.slice(5, word.length);
You can just `return "JavaScript"`, this is a very special case, so you don't need to assemble the return value programmatically

2023-01-20 23:45 UTC, joseph-w-valdez commented on string-manipulation-2/string-manipulation-2/src/capitalize-word.js
> +    result = result.slice(0, 4) + result.slice(4, 5).toUpperCase() + result.slice(5, word.length);
changes made https://i.imgur.com/1jdZNN1.png

2023-01-20 23:47 UTC, codingcodymiller approved these changes

2023-01-20 23:47 UTC, merged