completed express-post-json exercise
joseph-w-valdez/c1222-code-solutions pull request #90
Opened 2023-01-27 22:24 UTC by joseph-w-valdez

https://user-images.githubusercontent.com/117682160/215217430-11e042ee-27a4-42ee-968f-25ca002977e4.mp4

2023-01-27 22:58 UTC, RobertGardner requested changes
This is a bit more complex than it should be. I think you should simplify it before I Approve.

2023-01-27 22:58 UTC, RobertGardner commented on express-post-json/index.js
> +const students = [];
The instructions say to use `grades` and make it an empty object. You use an empty array instead. It looks like your code works, though.

2023-01-27 22:58 UTC, RobertGardner commented on express-post-json/index.js
> +  for (const prop in req.body) {
This is more complicated than it needs to be. All you really need to do is assign `req.body` to `student`. There's no need to manually copy all of its properties.

2023-01-27 23:28 UTC, joseph-w-valdez commented
https://user-images.githubusercontent.com/117682160/215224779-33c2e5fb-fa53-45e2-8f7d-aabe6b4656b3.mp4

2023-01-27 23:39 UTC, RobertGardner requested changes

2023-01-27 23:39 UTC, RobertGardner commented on express-post-json/index.js
> +  for (const prop in student) {
You're checking to make sure each of the properties has text in it. Good. Ideally, you'd check to make sure the object also has all the properties it should.

2023-01-27 23:39 UTC, RobertGardner commented on express-post-json/index.js
> +  students.id = nextId;
Oops. Shouldn't this be `student` instead of `students`? Check the output. You should get one object back and it should have an ID in it.

2023-01-27 23:39 UTC, RobertGardner commented on express-post-json/index.js
> +  res.json(students);
You are returning an array, not an object.

2023-01-28 00:48 UTC, joseph-w-valdez commented
https://user-images.githubusercontent.com/117682160/215231969-154126a2-7453-45ad-a784-349a6b9a2974.mp4

2023-01-30 21:34 UTC, RobertGardner approved these changes

2023-01-30 21:34 UTC, RobertGardner commented on express-post-json/index.js
> +    if (!student[prop] || !props.includes(prop)) {
Excellent! I like the use of `props`.

2023-01-30 21:40 UTC, joseph-w-valdez commented on express-post-json/index.js
> +    if (!student[prop] || !props.includes(prop)) {
Thanks!

2023-01-30 21:41 UTC, merged